name: Keep Supabase Alive

on:
  schedule:
    # 每三天运行一次 (UTC时间 0:00)
    - cron: '0 0 */3 * *' 
  workflow_dispatch:    # 允许你手动点击测试运行

jobs:
  ping-site:
    runs-on: ubuntu-latest
    steps:
      - name: Ping my website
        run: |
          echo "Pinging API to wake up Supabase..."
          curl -sL -D - https://xufan.vercel.app/api/keep-alive -o /dev/null

          # 建议直接使用 Vercel 的原始域名
          echo "Pinging Homepage to refresh Vercel cache..."
          curl -sL -D - https://xufan.vercel.app -o /dev/null